# Generated by Django 2.1 on 2018-08-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
