# Generated by Django 2.1 on 2018-08-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180812_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='score',
        ),
    ]
